ci: add release build script
harvester/harvester-ui-extension pull request #56
Opened 2024-12-30 09:16 UTC by a110605

### Summary
ci: add release build script

### PR Checklists
- Do we need to backport this PR change to the [Harvester Dashboard](https://github.com/harvester/dashboard)?
    - [ ] Yes, the relevant PR is at:
- Are backend engineers aware of UI changes?
    - [ ] Yes, the backend owner is:

### Related Issue #
https://github.com/harvester/harvester/issues/7089

### Test screenshot/video

### Extra technical notes summary

2024-12-30 09:19 UTC, a110605 commented on .github/workflows/build-and-upload.yaml
> +    name: Build & Upload Hosted
Not sure we still needed build host, from harvester/dashboard [README.md](https://github.com/harvester/dashboard#other-building-modes), this step is build `ui-index` file and push to GCP. e.g.
```
https://releases.rancher.com/harvester-ui/dashboard/latest/index.html
```

2025-01-02 17:54 UTC, torchiaf commented on .github/workflows/build-and-upload.yaml
> +    name: Build & Upload Hosted
I think we need it for the standalone mode

2025-01-05 19:40 UTC, torchiaf requested changes
I left some comments:

- `build-and-upload-harvester-plugin:` to be removed
- let's change the installation urls

After this, we could go ahead this way:

- Merge changes
- Push some test releases
- If the new artifacts looks good, replace the mock urls with the real ones
- Open a GH issue to the eio team to remove tests artifacts.

What do you think @a110605 ?

2025-01-05 19:40 UTC, torchiaf commented on .github/workflows/build-and-upload.yaml
> +          destination: releases.rancher.com/harvester-ui/dashboard/${{ steps.build-hosted.outputs.BUILD_HOSTED_LOCATION }}
Could you please replace the `destination` name using a mock before merging? Something like `test-release`.
This way we can push a test artifacts without overwrite the current master `branch` release and we will easily identify test artifacts to delete from cloud storage.

2025-01-05 19:40 UTC, torchiaf commented on .github/workflows/build-and-upload.yaml
> +          destination: releases.rancher.com/harvester-ui/${{ env.REPO }}
Change `destination` name , see comment above.

2025-01-05 19:40 UTC, torchiaf commented on .github/workflows/build-and-upload.yaml
> +  build-and-upload-harvester-plugin:
We can remove this Job.
- Rancher version 2.9 and lower is not compatible with the extension for Vue compatibility
- Rancher 2.10 and higher will use the extension installation

2025-01-06 03:15 UTC, a110605 commented on .github/workflows/build-and-upload.yaml
> +  build-and-upload-harvester-plugin:
Let's keep this job since harvester [dockerFile](https://github.com/harvester/harvester/blob/9609b9038f3724e584cfc432aaedd0274b6d8cc8/package/Dockerfile#L39) still pull below tar.gz

- https://releases.rancher.com/harvester-ui/plugin/harvester-latesttar.gz
- https://releases.rancher.com/harvester-ui/plugin/harvester-release-harvester-v1.5.tar.gz

2025-01-06 03:32 UTC, a110605 commented
> I left some comments:
> 
> * `build-and-upload-harvester-plugin` job to be removed
> * let's change the installation urls
> 
> After this, we could go ahead this way:
> 
> * Merge changes
> * Push some test releases
> * If the new artifacts looks good, replace the mock urls with the real ones
> * Open a GH issue to the eio team to remove tests artifacts.
> 
> What do you think @a110605 ?

Agreed. I updated all upload folder name to `test-release` and modified a [mock word](https://github.com/harvester/harvester-ui-extension/pull/56/commits/bad78f00bb757cb62332a9d11ae99bf018a76b3b) in setting page. 
We can merge this PR and push a new commit in main branch. Then use below `ui-index` to test in standalone mode 
```
https://releases.rancher.com/harvester-ui/dashboard/test-release/index.html
```

2025-01-06 07:32 UTC, houhoucoop approved these changes

2025-01-06 07:36 UTC, merged

2025-01-06 09:21 UTC, a110605 commented
Done testing build host artifact is good for standalone mode.

<img width="1494" alt="Screenshot 2025-01-06 at 5 08 55 PM" src="https://github.com/user-attachments/assets/03b8110a-bf2a-4c5c-9eeb-a7a00ca84d73" />